// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD36hEvfCsnL_4kOVncllMucgDWOD5UUNo',
    appId: '1:512282411888:web:84265289dab92610fb85b5',
    messagingSenderId: '512282411888',
    projectId: 'grosirmart-f9e28',
    authDomain: 'grosirmart-f9e28.firebaseapp.com',
    storageBucket: 'grosirmart-f9e28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE73qB3PPbH-3KT1Cg5IPI1YPOSBjUk2Y',
    appId: '1:512282411888:android:1c56c35f0e2e2701fb85b5',
    messagingSenderId: '512282411888',
    projectId: 'grosirmart-f9e28',
    storageBucket: 'grosirmart-f9e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBykfnvhhPSQDNf3Ahk583cZrVhq2Wi7pw',
    appId: '1:512282411888:ios:361dc71e0c227d42fb85b5',
    messagingSenderId: '512282411888',
    projectId: 'grosirmart-f9e28',
    storageBucket: 'grosirmart-f9e28.firebasestorage.app',
    iosBundleId: 'com.example.grosirMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBykfnvhhPSQDNf3Ahk583cZrVhq2Wi7pw',
    appId: '1:512282411888:ios:361dc71e0c227d42fb85b5',
    messagingSenderId: '512282411888',
    projectId: 'grosirmart-f9e28',
    storageBucket: 'grosirmart-f9e28.firebasestorage.app',
    iosBundleId: 'com.example.grosirMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD36hEvfCsnL_4kOVncllMucgDWOD5UUNo',
    appId: '1:512282411888:web:dacf07f9356c62d7fb85b5',
    messagingSenderId: '512282411888',
    projectId: 'grosirmart-f9e28',
    authDomain: 'grosirmart-f9e28.firebaseapp.com',
    storageBucket: 'grosirmart-f9e28.firebasestorage.app',
  );
}
